build: don't use IMA (-combine) due to build error
IMA causes the following error. Bleh.

gcc -ggdb -Wall -pipe -pthread -o L2O3 -combine sock.c bad_net.c
In file included from /usr/include/sys/socket.h:40,
                 from bad_net.c:2:
/usr/include/bits/socket.h:425: error: conflicting types for ‘recvmmsg’
/usr/include/bits/socket.h:425: error: previous declaration of ‘recvmmsg’ was here
make: *** [L2O3] Error 1